-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;


CREATE TABLE category (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE product (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    product_name VARCHAR(255) NOT NULL,
    price DECIMAL(11, 10)
)